parameters:
    yauhenko.rest.env: '%kernel.environment%'
    yauhenko.rest.types_class: 'App\Types'
    yauhenko.rest.cache_dir: '%kernel.cache_dir%'
    yauhenko.rest.project_dir: '%kernel.project_dir%'
    yauhenko.rest.controllers_dir: '%kernel.project_dir%/src/Controller'

services:
    _defaults:
        autowire: true
        autoconfigure: true
    Yauhenko\RestBundle\EventSubscriber\ControllerArgumentsSubscriber: ~
    Yauhenko\RestBundle\EventSubscriber\ExceptionSubscriber: ~
    Yauhenko\RestBundle\EventSubscriber\RequestSubscriber: ~
    Yauhenko\RestBundle\EventSubscriber\ResponseSubscriber: ~
    Yauhenko\RestBundle\Service\ObjectBuilder: ~
    Yauhenko\RestBundle\Controller\Docs: ~
